services:
  postgres:
    image: pgvector/pgvector:pg17-trixie
    container_name: sikds-postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: sikds
      POSTGRES_USER: sikds_user
      POSTGRES_PASSWORD: '8!XpLq2@RmZ7VtK'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sikds_user -d sikds"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
